[project]
name = "sidechart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "marabsatt", email = "mitchelrabsatt@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "diagrams>=0.24.4",
    "dotenv>=0.9.9",
    "fastapi>=0.124.0",
    "ib-insync>=0.9.86",
    "massive>=2.8.0",
    "nest-asyncio>=1.6.0",
    "numpy>=2.0.0",
    "openai>=2.14.0",
    "pandas>=2.3.3",
    "polygon>=1.2.8",
    "python-dotenv>=1.2.1",
    "requests>=2.32.0",
    "riskfolio-lib>=7.0.1",
    "uvicorn>=0.38.0",
    "yfinance>=0.2.66",
]

[project.scripts]
sidechart = "sidechart:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "src/agents/research",
    "src/agents/supervisor",
]
